spring.application.name=SafeStep
server.port=8080

# Conexiunea automată pentru Render (va citi variabila pusă de tine)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Setări pentru generarea tabelelor în Postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true