spring.application.name=SafeStep
server.port=8080

# Folosim baza de date H2 (in-memory) pentru Render
spring.datasource.url=jdbc:h2:mem:safestepdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permite crearea automată a tabelelor la pornire
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true